POST http://localhost:5000/conversiones
Content-Type: application/json

{
  "duracion_original": 12.5,
  "frecuencia_muestreo_original": 44100,
  "frecuencia_muestreo_objetivo": 16000,
  "profundidad_bits": 16,
  "formato": "mp3"
}
